# Generated by Django 3.2.20 on 2023-11-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='colleges_can_edit',
            field=models.ManyToManyField(blank=True, related_name='editors', to='programs.College'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='departments_can_edit',
            field=models.ManyToManyField(blank=True, related_name='editors', to='programs.Department'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
