# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-24 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
                ('abrev', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_comment', models.TextField(blank=True, null=True)),
                ('secondary_comment', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('bldg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledata.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('postal', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_comment', models.TextField(blank=True, null=True)),
                ('secondary_comment', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_udpated', models.DateTimeField(blank=True, null=True)),
                ('bldg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledata.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.BooleanField(default=True)),
                ('last_name', models.CharField(max_length=25)),
                ('suffix', models.CharField(blank=True, max_length=3, null=True)),
                ('name_title', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=14)),
                ('middle', models.CharField(blank=True, max_length=15, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('email_machine', models.CharField(blank=True, max_length=255, null=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('listed', models.BooleanField(default=True)),
                ('cellphone', models.CharField(blank=True, max_length=50, null=True)),
                ('bldg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledata.Building')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledata.Department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teledata.Organization'),
        ),
    ]
