# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-28 15:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='import_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
