# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-31 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0002_auto_20191028_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='last_udpated',
            new_name='last_updated',
        ),
    ]
