# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-01 17:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0003_auto_20191031_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedTeledataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.NullBooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=14, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('sort_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('job_position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_id', models.IntegerField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('bldg_id', models.IntegerField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('from_table', models.CharField(max_length=255)),
            ],
        ),
    ]
