# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-04 14:29


from django.db import migrations


class Migration(migrations.Migration):

    def forward(apps, schema_editor):
        if schema_editor.connection.vendor == 'mysql':
            migrations.RunSQL('CREATE FULLTEXT INDEX teledata_name_index ON `teledata_combinedteledataview` (`first_name`, `last_name`)',)

    def reverse(apps, schema_editor):
        if schema_editor.connection.vendor == 'mysql':
            migrations.RunSQL('DROP INDEX teledata_name_index on teledata_combinedteledataview',)

    dependencies = [
        ('teledata', '0004_combinedteledataview'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]
