# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-04 14:29


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0004_combinedteledataview'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX teledata_name_index ON `teledata_combinedteledataview` (`first_name`, `last_name`)',),
            ('DROP INDEX teledata_name_index on teledata_combinedteledataview',),
            hints={'target_db': 'mysql'}
        )
    ]
