# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 15:53


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0006_auto_20191106_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombinedTeledataView',
            new_name='CombinedTeledata',
        ),
    ]
