# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-07 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0007_auto_20191107_1553'),
    ]

    operations = [
        migrations.RunSQL(
            ('CREATE FULLTEXT INDEX teledata_fullname_index ON `teledata_combinedteledata` (`name`)',),
            ('DROP INDEX teledata_fullname_index on teledata_combinedteledata',)
        )
    ]
