# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 13:58
from __future__ import unicode_literals

from django.db import migrations, models

from teledata.models import CombinedTeledata

def forward_migration(apps, schema_editor):
    CombinedTeledata.objects.update_data()

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0008_auto_20191107_1951'),
    ]

    operations = [
        # Alter db engine so we can have multiple fulltext indexes
        migrations.RunSQL(
            ('ALTER TABLE `teledata_combinedteledata` ENGINE = MyISAM'),
            ('ALTER TABLE `teledata_combinedteledata` ENGINE = InnoDB')
        ),
        # Truncate all the data in the table
        migrations.RunSQL(
            ('TRUNCATE TABLE teledata_combinedteledata'),
            ('TRUNCATE TABLE teledata_combinedteledata')
        ),
        # Remove the primary key as we're renaming it
        migrations.RemoveField(
            model_name='combinedteledata',
            name='id'
        ),
        # Add the new primary key
        migrations.AddField(
            model_name='combinedteledata',
            name='pkid',
            field=models.AutoField(primary_key=True, serialize=False)
        ),
        # Add the new id (non pk) field
        migrations.AddField(
            model_name='combinedteledata',
            name='id',
            field=models.IntegerField(primary_key=False, auto_created=False),
        ),
        migrations.RunPython(forward_migration, reverse_migration)
    ]
