# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 13:58


from django.db import migrations, models

from teledata import models

def forward_migration(apps, schema_editor):
    models.CombinedTeledata.objects.update_data()

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    def forward_prep(apps, schema):
        if schema.connection.vendor == 'mysql':
            migrations.RunSQL('ALTER TABLE `teledata_combinedteledata` ENGINE = MyISAM')

        CombinedTeledata = apps.get_model('teledata', 'CombinedTeledata')
        CombinedTeledata.objects.all().delete()

    def reverse_prep(apps, schema):
        if schema.connection.vendor == 'mysql':
            migrations.RunSQL('ALTER TABLE `teledata_combinedteledata` ENGINE = InnoDB')

        CombinedTeledata = apps.get_model('teledata', 'CombinedTeledata')
        CombinedTeledata.objects.all().delete()

    dependencies = [
        ('teledata', '0008_auto_20191107_1951'),
    ]

    operations = [
        # Alter db engine so we can have multiple fulltext indexes
        migrations.RunPython(forward_prep, reverse_prep),
        # Remove the primary key as we're renaming it
        migrations.RemoveField(
            model_name='combinedteledata',
            name='id'
        ),
        # Add the new primary key
        migrations.AddField(
            model_name='combinedteledata',
            name='pkid',
            field=models.AutoField(primary_key=True, serialize=False)
        ),
        # Add the new id (non pk) field
        migrations.AddField(
            model_name='combinedteledata',
            name='id',
            field=models.IntegerField(primary_key=False, auto_created=False, null=True),
        ),
        migrations.RunPython(forward_migration, reverse_migration)
    ]
