# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0009_auto_20191108_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedteledata',
            name='id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
