# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0011_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedteledata',
            name='keywords_combined',
            field=models.ManyToManyField(db_constraint=False, related_name='combined', to='teledata.Keyword'),
        ),
    ]
