# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0012_combinedteledata_keywords_combined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='listed',
            new_name='active',
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='combinedteledata',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
