# Generated by Django 3.1.1 on 2020-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0013_auto_20200309_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinedteledata',
            name='alpha',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
