# Generated by Django 3.1.1 on 2021-06-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
        ('teledata', '0014_auto_20200922_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teledata_departments', to='units.unit'),
        ),
        migrations.AddField(
            model_name='organization',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teledata_organizations', to='units.unit'),
        ),
    ]
