# Generated by Django 3.1.1 on 2021-06-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org_units', '0004_auto_20210616_1741'),
        ('teledata', '0015_auto_20210611_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_unit',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organization_unit',
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teledata_department', to='org_units.unit'),
        ),
        migrations.AddField(
            model_name='organization',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teledata_organization', to='org_units.unit'),
        ),
    ]
