# Generated by Django 3.2.4 on 2021-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0015_auto_20210629_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
