# Generated by Django 3.2.25 on 2026-09-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_remove_researcher_teledata_record'),
        ('teledata', '0016_staff_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinedteledata',
            name='keywords_combined',
        ),
        migrations.RemoveField(
            model_name='department',
            name='bldg',
        ),
        migrations.RemoveField(
            model_name='department',
            name='org',
        ),
        migrations.RemoveField(
            model_name='department',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='bldg',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bldg',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='dept',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='CombinedTeledata',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
