# Generated by Django 3.2.8 on 2021-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_college_department_division_employee_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
