# Generated by Django 3.2.8 on 2021-11-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_alter_employee_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='sanitized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='sanitized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='sanitized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='sanitized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
