# Generated by Django 3.1.1 on 2021-06-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20210616_1741'),
        ('teledata', '0016_auto_20210616_1741'),
        ('programs', '0047_auto_20210616_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentUnit',
        ),
        migrations.DeleteModel(
            name='OrganizationUnit',
        ),
        migrations.AddField(
            model_name='unit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_units', to='units.unit'),
        ),
    ]
