# Generated by Django 3.2.8 on 2021-11-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20211110_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='college',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='division',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organization',
        ),
        migrations.AddField(
            model_name='employee',
            name='colleges',
            field=models.ManyToManyField(related_name='employees', to='units.College'),
        ),
        migrations.AddField(
            model_name='employee',
            name='departments',
            field=models.ManyToManyField(related_name='employees', to='units.Department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='divisions',
            field=models.ManyToManyField(related_name='employees', to='units.Division'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organizations',
            field=models.ManyToManyField(related_name='employees', to='units.Organization'),
        ),
    ]
