# Generated by Django 3.2.25 on 2025-11-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastshow',
            name='feed_url',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
