# Generated by Django 3.2.25 on 2025-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcastshow_feed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
