# Generated by Django 3.2.25 on 2025-11-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_podcastepisode_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.podcastshow'),
        ),
    ]
