# Generated by Django 3.2.25 on 2025-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_alter_podcastepisode_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='guid',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
