# Generated by Django 3.2.25 on 2025-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_podcastepisode_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastepisode',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
