# Generated by Django 3.2.25 on 2025-11-17 16:17

from django.db import migrations, models
import django.db.models.deletion

def create_default_category(apps, schema_editor):
    PodcastCategory = apps.get_model('podcasts', 'PodcastCategory')
    # See if a category with ID 1 exists, and if so, delete it
    try:
        category = PodcastCategory.objects.get(pk=1)
        category.delete()
    except PodcastCategory.DoesNotExist:
        pass
    finally:
        PodcastCategory.objects.create(id=1, title='Uncategorized', description='')


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_podcastepisode_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RunPython(create_default_category),
        migrations.AlterField(
            model_name='podcastepisode',
            name='guid',
            field=models.CharField(db_index=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='podcastshow',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='episodes', to='podcasts.podcastcategory'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podcasts', to='podcasts.podcastcategory'),
        ),
    ]
