# Generated by Django 3.2.25 on 2025-11-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_auto_20251117_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisodeHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='podcasts.podcastepisode')),
            ],
        ),
    ]
