# Generated by Django 3.2.25 on 2025-11-20 17:11

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_podcastepisodehighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastshow',
            name='show_image_medium',
            field=models.ImageField(blank=True, editable=False, null=True, storage=core.storage_backends.PodcastImageStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='show_image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, storage=core.storage_backends.PodcastImageStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='podcastshow',
            name='show_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PodcastImageStorage, upload_to=''),
        ),
    ]
