# Generated by Django 3.2.25 on 2026-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0010_auto_20251120_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
