# Generated by Django 3.2.25 on 2025-02-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0064_alter_programauditdata_jobs_source'),
        ('marketing', '0003_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='programs.Program'),
        ),
    ]
