# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 20:13


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('last_imported', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, default=settings.APP_NAME, max_length=255, null=True)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor', models.CharField(blank=True, max_length=500, null=True)),
                ('width_full', models.IntegerField()),
                ('height_full', models.IntegerField()),
                ('download_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, default=settings.APP_NAME, max_length=255, null=True)),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_imagetag_synonyms_+', to='images.ImageTag')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.ImageTag'),
        ),
    ]
