# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(default='UCF Search Service', max_length=255),
        ),
    ]
