# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-09 13:55


import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='name',
            field=core.models.LowercaseCharField(max_length=255, unique=True),
        ),
    ]
