# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20191211_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.CharField(blank=True, default='UCF Search Service', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
