# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20191211_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetag',
            name='synonym',
        ),
        migrations.AddField(
            model_name='imagetag',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_imagetag_synonyms_+', to='images.ImageTag'),
        ),
    ]
