# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 16:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_photo_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
