# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20191211_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='source',
            field=models.CharField(blank=True, default='UCF Search Service', max_length=255, null=True),
        ),
    ]
