# Generated by Django 3.2.25 on 2026-09-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetag',
            name='synonyms',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageTag',
        ),
    ]
