# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_imagetag_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.ImageTag'),
        ),
    ]
