# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20191212_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='last_imported',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
