# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-02 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teledata', '0012_combinedteledata_keywords_combined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('teledata_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teledata.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Researcher'),
        ),
    ]
