# Generated by Django 3.1.1 on 2021-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20210428_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchwork',
            name='bibtex_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
