# Generated by Django 3.2.4 on 2021-10-11 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchwork_bibtex_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('aa_article_id', models.IntegerField()),
                ('article_title', models.CharField(max_length=1024)),
                ('journal_name', models.CharField(max_length=512)),
                ('article_year', models.IntegerField()),
                ('journal_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('journal_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('first_page', models.CharField(blank=True, max_length=26, null=True)),
                ('last_page', models.CharField(blank=True, max_length=26, null=True)),
            ],
            bases=('research.researchwork',),
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('aa_book_id', models.IntegerField()),
                ('isbn', models.CharField(max_length=16)),
                ('book_title', models.CharField(max_length=320)),
                ('chapter_title', models.CharField(max_length=320)),
                ('bisac', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=40, null=True)),
                ('publish_year', models.DateField(blank=True, null=True)),
            ],
            bases=('research.researchwork',),
        ),
        migrations.CreateModel(
            name='ConferenceProceeding',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('aa_article_id', models.IntegerField()),
                ('proceeding_title', models.CharField(max_length=1024)),
                ('journal_name', models.CharField(max_length=512)),
                ('article_year', models.DateField(blank=True, null=True)),
                ('journal_volume', models.CharField(blank=True, max_length=50, null=True)),
                ('journal_issue', models.CharField(blank=True, max_length=50, null=True)),
                ('first_page', models.CharField(blank=True, max_length=26, null=True)),
                ('last_page', models.CharField(blank=True, max_length=26, null=True)),
            ],
            bases=('research.researchwork',),
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('aa_grant_id', models.IntegerField()),
                ('agency_name', models.CharField(max_length=64)),
                ('grant_name', models.CharField(max_length=256)),
                ('duration_years', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=64, null=True)),
                ('total_dollars', models.IntegerField()),
                ('is_research', models.BooleanField()),
                ('principle_investigator', models.BooleanField()),
            ],
            bases=('research.researchwork',),
        ),
        migrations.CreateModel(
            name='HonorificAward',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('aa_award_id', models.IntegerField()),
                ('governing_society_name', models.CharField(max_length=1024)),
                ('award_name', models.CharField(max_length=255)),
                ('award_received_name', models.CharField(max_length=128)),
                ('award_received_year', models.DateField()),
            ],
            bases=('research.researchwork',),
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='bibtex_string',
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='title',
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='work_put_code',
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='work_type',
        ),
        migrations.AddField(
            model_name='researcher',
            name='aa_person_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('aa_book_id', models.IntegerField()),
                ('isbn', models.CharField(max_length=16)),
                ('book_title', models.CharField(max_length=320)),
                ('bisac', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=40, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
            ],
            bases=('research.researchwork',),
        ),
        migrations.CreateModel(
            name='ClinicalTrial',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('nct_id', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=2048)),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('study_type', models.CharField(max_length=64)),
                ('sponsor', models.CharField(max_length=256)),
                ('allocation', models.CharField(blank=True, max_length=32, null=True)),
                ('phase', models.CharField(blank=True, max_length=32, null=True)),
                ('recruitment_status', models.CharField(blank=True, max_length=32, null=True)),
                ('investigators', models.TextField(blank=True, null=True)),
            ],
            bases=('research.researchwork',),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('researchwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='research.researchwork')),
                ('patent_id', models.IntegerField()),
                ('patent_type', models.CharField(max_length=40)),
                ('patent_kind', models.CharField(max_length=3)),
                ('patent_date', models.DateField()),
                ('country', models.CharField(max_length=2)),
                ('claims', models.IntegerField()),
                ('abstract', models.TextField(blank=True, null=True)),
            ],
            bases=('research.researchwork',),
        ),
    ]
