# Generated by Django 3.2.4 on 2021-10-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20211011_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=19, null=True, unique=True),
        ),
    ]
