# Generated by Django 3.2.4 on 2021-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_alter_researcher_orcid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
