# Generated by Django 3.2.4 on 2021-10-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_alter_researcher_orcid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='publish_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
