# Generated by Django 3.2.4 on 2021-10-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_auto_20211013_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceproceeding',
            name='article_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
