# Generated by Django 3.2.4 on 2021-10-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_alter_conferenceproceeding_article_year'),
    ]

    operations = [
        # Dropped and re-added rather than altered in place: PostgreSQL
        # can't cast a date column to an integer. Production MySQL
        # applied the original AlterField, and the end state is the same.
        migrations.RemoveField(
            model_name='honorificaward',
            name='award_received_year',
        ),
        migrations.AddField(
            model_name='honorificaward',
            name='award_received_year',
            field=models.IntegerField(),
        ),
    ]
