# Generated by Django 3.2.4 on 2021-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_alter_honorificaward_award_received_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_title',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
