# Generated by Django 3.2.4 on 2021-10-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_patent_patent_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchwork',
            options={'default_related_name': '%(class)s'},
        ),
        migrations.RemoveField(
            model_name='researchwork',
            name='researcher',
        ),
        migrations.AddField(
            model_name='researchwork',
            name='researchers',
            field=models.ManyToManyField(related_name='works', to='research.Researcher'),
        ),
    ]
