# Generated by Django 3.2.4 on 2021-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20211018_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='patent_id',
            field=models.CharField(max_length=10),
        ),
    ]
