# Generated by Django 3.2.4 on 2021-10-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_alter_patent_patent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchwork',
            options={},
        ),
    ]
