# Generated by Django 3.2.8 on 2021-11-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teledata', '0016_staff_employee_id'),
        ('units', '0003_alter_employee_prefix'),
        ('research', '0013_alter_researchwork_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='employee_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='researcher', to='units.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researcher',
            name='teledata_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='researcher_records', to='teledata.staff'),
        ),
    ]
