# Generated by Django 3.2.8 on 2021-11-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_auto_20211105_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='researcher',
            name='research_terms',
            field=models.ManyToManyField(related_name='researchers', to='research.ResearchTerm'),
        ),
    ]
