# Generated by Django 3.2.25 on 2026-09-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_auto_20211122_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='teledata_record',
        ),
    ]
