# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20180409_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_profiles',
        ),
        migrations.AddField(
            model_name='programprofile',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.Program'),
            preserve_default=False,
        ),
    ]
