# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 20:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_level_abbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='abbr',
        ),
        migrations.AddField(
            model_name='career',
            name='abbr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
