# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 17:15


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_auto_20180409_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='parent_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subplans', to='programs.Program'),
        ),
    ]
