# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_parent_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
