# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDescriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='credit_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programprofile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='programs.Program'),
        ),
        migrations.AddField(
            model_name='programdescription',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.ProgramDescriptionType'),
        ),
        migrations.AddField(
            model_name='programdescription',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='programs.Program'),
        ),
    ]
