# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20180412_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programdescription',
            old_name='profile_type',
            new_name='description_type',
        ),
    ]
