# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20180419_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programdescription',
            unique_together=set([('description_type', 'program')]),
        ),
    ]
