# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 16:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20180419_1614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programprofile',
            unique_together=set([('profile_type', 'program')]),
        ),
    ]
