# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 19:12


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_auto_20180419_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('plan_code', 'subplan_code')]),
        ),
    ]
