# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20180419_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
