# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20180502_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=10)),
                ('subplan_code', models.CharField(blank=True, max_length=10, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.College')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_code', models.CharField(max_length=10)),
                ('plan_code', models.CharField(max_length=10)),
                ('subplan_code', models.CharField(blank=True, max_length=10, null=True)),
                ('skip', models.BooleanField(default=False)),
                ('required_fees', models.ManyToManyField(to='programs.Fee')),
            ],
        ),
    ]
