# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_auto_20180502_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='has_online',
            field=models.BooleanField(default=False),
        ),
    ]
