# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 14:54


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_collegeoverride_tuitionoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='nonresident_tuition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='resident_tuition',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='tuition_type',
            field=models.CharField(blank=True, choices=[('SCH', 'Single Credit Hour'), ('TRM', 'Term'), ('CRS', 'Course'), ('ANN', 'Annual')], max_length=3, null=True),
        ),
    ]
