# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 15:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_auto_20190107_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionoverride',
            name='required_fees',
            field=models.ManyToManyField(blank=True, to='programs.Fee'),
        ),
    ]
