# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_auto_20190114_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='plan_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='subplan_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
