# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_auto_20190114_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionoverride',
            name='required_fees',
            field=models.ManyToManyField(blank=True, to='programs.Fee'),
        ),
    ]
