# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 16:02


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20190124_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
