# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0018_program_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='cip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
