# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0019_program_cip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('display', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcomeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_full_time', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('continuing_edication', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('avg_annual_earnings', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='programs.AcademicYear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='programs.Program')),
            ],
        ),
    ]
