# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0020_academicyear_programoutcomestat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programoutcomestat',
            old_name='continuing_edication',
            new_name='continuing_education',
        ),
    ]
