# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-02 21:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_auto_20191125_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.DecimalField(decimal_places=4, max_digits=6)),
                ('two_digit', models.IntegerField(blank=True)),
                ('four_digit', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('six_digit', models.DecimalField(blank=True, decimal_places=4, max_digits=6)),
            ],
        ),
    ]
