# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_cip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='cip',
            name='four_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cip',
            name='six_digit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
