# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 15:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0023_auto_20191203_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cip',
            old_name='two_digit',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='cip',
            old_name='four_digit',
            new_name='precise',
        ),
        migrations.RenameField(
            model_name='cip',
            old_name='six_digit',
            new_name='subarea',
        ),
    ]
