# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0025_auto_20191204_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cip',
            name='version',
            field=models.CharField(choices=[('2010', '2010'), ('2020', '2020')], default='2020', max_length=4),
        ),
    ]
