# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0026_cip_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='cip',
            name='next_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_versions', to='programs.CIP'),
        ),
        migrations.AddField(
            model_name='cip',
            name='prev_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_versions', to='programs.CIP'),
        ),
    ]
