# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0028_auto_20191204_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cip_code',
        ),
        migrations.AddField(
            model_name='program',
            name='cip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.CIP'),
        ),
        migrations.AlterField(
            model_name='cip',
            name='version',
            field=models.CharField(choices=[('2010', '2010'), ('2020', '2020')], default=b'2010', max_length=4),
        ),
    ]
