# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0029_auto_20191205_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='cip',
        ),
        migrations.AddField(
            model_name='program',
            name='cip',
            field=models.ManyToManyField(blank=True, to='programs.CIP'),
        ),
    ]
