# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0031_auto_20191206_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programoutcomestat',
            name='continuing_education',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='programoutcomestat',
            name='employed_full_time',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
