# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0032_auto_20191206_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(choices=[('2010', '2010')], default=b'2010', max_length=4)),
                ('code', models.CharField(max_length=7)),
                ('cip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='programs.CIP')),
                ('jobs', models.ManyToManyField(related_name='occupations', to='programs.JobPosition')),
            ],
        ),
    ]
