# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-09 19:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0035_auto_20191212_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='programs', to='programs.ProgramOutcomeStat'),
        ),
    ]
