# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0036_auto_20200309_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDeadlineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('admission_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadlines', to='programs.AdmissionTerm')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadlines', to='programs.Career')),
                ('deadline_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadlines', to='programs.AdmissionDeadlineType')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='application_deadline_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='application_requirements',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), blank=True, null=True, size=20),
        ),
        migrations.AddField(
            model_name='program',
            name='application_deadlines',
            field=models.ManyToManyField(blank=True, to='programs.ApplicationDeadline'),
        ),
    ]
