# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 20:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0036_auto_20200309_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
