# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-05 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0037_auto_20200427_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeadline',
            name='display',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
