# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0038_auto_20200518_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='graduate_slate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
