# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-05 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0038_applicationdeadline_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeadline',
            name='display',
        ),
    ]
