# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 16:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0039_program_graduate_slate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='offered',
            field=models.BooleanField(default=True),
        ),
    ]
