# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-11 18:35


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0040_program_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='offered',
            new_name='has_locations',
        ),
    ]
