# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-27 19:49


from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0041_auto_20200811_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDeadlineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('admission_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadlines', to='programs.AdmissionTerm')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadlines', to='programs.Career')),
                ('deadline_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadlines', to='programs.AdmissionDeadlineType')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='application_deadline_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='application_requirements',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), blank=True, null=True, size=20),
        ),
        migrations.AddField(
            model_name='program',
            name='application_deadlines',
            field=models.ManyToManyField(blank=True, related_name='programs', to='programs.ApplicationDeadline'),
        ),
    ]
