# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-20 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0042_auto_20200427_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='application_deadline_details',
        ),
    ]
