# Generated by Django 3.1.1 on 2020-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0043_remove_program_application_deadline_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='version',
            field=models.CharField(choices=[('2010', '2010'), ('2020', '2020')], default='2010', max_length=4),
        ),
        migrations.AlterField(
            model_name='employmentprojection',
            name='report',
            field=models.CharField(choices=[('1828', '2018-2028')], default='1828', max_length=4),
        ),
        migrations.AlterField(
            model_name='soc',
            name='version',
            field=models.CharField(choices=[('2010', '2010')], default='2010', max_length=4),
        ),
    ]
