# Generated by Django 3.1.1 on 2020-10-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0044_auto_20200922_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionoverride',
            name='skip',
            field=models.BooleanField(default=False, help_text='The tuition values for the program will not be updated during the tuition import when this is checked.'),
        ),
    ]
