# Generated by Django 3.1.1 on 2021-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0046_auto_20210629_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='version',
            field=models.CharField(choices=[('2010', '2010'), ('2018', '2018')], default='2010', max_length=4),
        ),
    ]
