# Generated by Django 3.1.1 on 2021-06-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20210616_1741'),
        ('programs', '0047_auto_20210616_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_departments', to='units.unit'),
        ),
    ]
