# Generated by Django 3.2.8 on 2021-11-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20211110_1642'),
        ('programs', '0047_auto_20210629_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='unit_college',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_college', to='units.college'),
        ),
        migrations.AddField(
            model_name='department',
            name='unit_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_department', to='units.department'),
        ),
    ]
