# Generated by Django 3.2.8 on 2021-11-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20211110_1642'),
        ('programs', '0048_auto_20211110_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='unit_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_department', to='units.department'),
        ),
    ]
