# Generated by Django 3.2.8 on 2022-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0049_auto_20211110_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15)),
                ('short_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='cip',
            name='version',
            field=models.CharField(choices=[('2010', '2010'), ('2020', '2020')], default='2020', max_length=4),
        ),
        migrations.AlterField(
            model_name='employmentprojection',
            name='report',
            field=models.CharField(choices=[('1828', '2018-2028'), ('1929', '2019-2029')], default='1929', max_length=4),
        ),
        migrations.AlterField(
            model_name='soc',
            name='version',
            field=models.CharField(choices=[('2010', '2010'), ('2018', '2018')], default='2018', max_length=4),
        ),
    ]
