# Generated by Django 3.2.13 on 2022-10-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0051_program_start_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentprojection',
            name='report',
            field=models.CharField(choices=[('1828', '2018-2028'), ('1929', '2019-2029'), ('2131', '2021-2031')], default='2131', max_length=4),
        ),
        migrations.CreateModel(
            name='WeightedJobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_positions', to='programs.jobposition')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_careers', to='programs.program')),
            ],
        ),
    ]
