# Generated by Django 3.2.13 on 2022-11-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0052_auto_20221019_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightedjobposition',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weighted_jobs', to='programs.program'),
        ),
    ]
