# Generated by Django 3.2.20 on 2023-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0055_programimportrecord'),
    ]

    def forward(apps, schema_editor):
        WeightedJobPosition = apps.get_model('programs', 'WeightedJobPosition')
        for row in WeightedJobPosition.objects.all():
            program = row.program
            program.jobs.add(row.job)
            program.save()


    operations = [
        migrations.AddField(
            model_name='program',
            name='jobs',
            field=models.ManyToManyField(related_name='programs', to='programs.JobPosition'),
        ),
        migrations.RunPython(
            forward,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.DeleteModel(
            name='WeightedJobPosition',
        ),
    ]
