# Generated by Django 3.2.20 on 2023-11-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0055_programimportrecord'),
    ]

    def forward(apps, schema_editor):
        WeightedJobPosition = apps.get_model('programs', 'WeightedJobPosition')
        for row in WeightedJobPosition.objects.all():
            print(row)


    operations = [
        migrations.RunPython(
            forward,
            reverse_code=migrations.RunPython.noop
        ),
        # migrations.AddField(
        #     model_name='program',
        #     name='jobs',
        #     field=models.ManyToManyField(related_name='programs', to='programs.JobPosition'),
        # ),
        # migrations.DeleteModel(
        #     name='WeightedJobPosition',
        # ),
    ]
