# Generated by Django 3.2.20 on 2024-03-04 18:47

from django.db import migrations, models
import django.db.models.deletion

def forwards(apps, schema_editor):
    """
    Creates an audit object for each
    program that already exists.
    """
    Program = apps.get_model('programs', 'Program')
    ProgramAuditData = apps.get_model('programs', 'ProgramAuditData')
    for program in Program.objects.all():
        ProgramAuditData.objects.create(
            program=program
        )

def reverse(apps, schema_editor):
    """
    Deletes all ProgramAuditData objects
    """
    ProgramAuditData = apps.get_model('programs', 'ProgramAuditData')
    ProgramAuditData.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0056_auto_20231128_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramAuditData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_source', models.TextField(default='U.S. Bureau of Labor Statistics - Classification of Instructional Programs (CIP) to Standard Occupational Classification (SOC) mapping done for employment projection reports')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programs.program')),
            ],
        ),
        migrations.RunPython(
            code=forwards,
            reverse_code=reverse
        )
    ]
