# Generated by Django 3.2.20 on 2024-03-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0057_auto_20240304_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programauditdata',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_data', to='programs.program'),
        ),
    ]
