# Generated by Django 3.2.20 on 2024-07-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0059_program_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='highlights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
