# Generated by Django 3.2.20 on 2024-07-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0060_alter_program_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='highlights',
            field=models.JSONField(default=list),
        ),
    ]
