# Generated by Django 3.2.20 on 2024-07-24 15:13
import json

from django.db import migrations


class Migration(migrations.Migration):

    def forward(apps, schema_editor):
        Program = apps.get_model('programs', 'Program')
        for row in Program.objects.filter(highlights__isnull=False):
            highlights = row.highlights
            if isinstance(highlights, str):
                highlights = json.loads(highlights)

            row.highlights = highlights
            row.save()


    dependencies = [
        ('programs', '0061_alter_program_highlights'),
    ]

    operations = [
        migrations.RunPython(
            forward,
            reverse_code=migrations.RunPython.noop
        )
    ]
