# Generated by Django 3.2.25 on 2025-01-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0062_auto_20240724_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='program',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='programs', to='programs.JobPosition'),
        ),
    ]
