# Generated by Django 3.2.25 on 2025-01-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0063_auto_20250116_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programauditdata',
            name='jobs_source',
            field=models.TextField(default=''),
        ),
    ]
