# Generated by Django 3.2.25 on 2025-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_quote_tags'),
        ('programs', '0064_alter_programauditdata_jobs_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='quotes',
            field=models.ManyToManyField(blank=True, related_name='programs', to='marketing.Quote'),
        ),
    ]
