from django.conf.urls import url

from locations.views import *

urlpatterns = [
    url(r'^campuses/$',
        CampusListView.as_view(),
        name='api.campuses.list'
        ),
    url(r'^campuses/kml/$',
        CampusListKMLView.as_view(),
        name='api.campuses.kml'
        ),
    url(
        r'^campuses/types/$',
        CampusTypeListView.as_view(),
        name='api.campuses.types.list'
        ),
    url(r'^facilities/$',
        FacilityListView.as_view(),
        name='api.facilities.list'
        ),
    url(r'^facilities/kml/$',
        FacilityListKMLView.as_view(),
        name='api.facilities.kml'
        ),
    url(r'^parking/$',
        ParkingLotListView.as_view(),
        name='api.parking.list'
        ),
    url(r'^parking/kml/$',
        ParkingLotListKMLView.as_view(),
        name='api.parking.kml'
        ),
    url(r'^parking/permit-types/$',
        ParkingPermitTypeListView.as_view(),
        name='api.parking.permittypes.list'
        ),
    url(r'^parking/zones/$',
        ParkingZoneListView.as_view(),
        name='api.parking.zones.list'
        ),
    url(r'^parking/zones/kml/$',
        ParkingZoneListKMLView.as_view(),
        name='api.parking.zones.kml'
        ),
    url(r'^locations/$',
        LocationListView.as_view(),
        name='api.locations.list'
        ),
    url(r'^locations/kml/$',
        LocationListKMLView.as_view(),
        name='api.locations.kml'
        ),
    url(r'^locations/types/$',
        LocationTypeListView.as_view(),
        name='api.locations.types.list'
        ),
    url(r'^points-of-interest/$',
        PointOfInterestListView.as_view(),
        name='api.pointsofinterest.list'
        ),
    url(r'^points-of-interest/kml/$',
        PointOfInterestListKMLView.as_view(),
        name='api.pointsofinterest.kml'
        ),
    url(r'^points-of-interest/types/$',
        PointTypeListView.as_view(),
        name='api.pointsofinterest.types.list'
        ),
    url(r'^groups/$',
        GroupListView.as_view(),
        name='api.groups.list'
        ),
    url(r'^groups/kml/$',
        GroupListKMLView.as_view(),
        name='api.groups.kml'
        ),
    url(r'^groups/types/$',
        GroupTypeListView.as_view(),
        name='api.groups.types.list'
        ),
]
