# Generated by Django 3.2.25 on 2026-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('profile_link', models.URLField(blank=True, max_length=500, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('googlemap_lat', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('googlemap_lng', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('illustrated_lat', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('illustrated_lng', models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True)),
                ('poly_coords', models.TextField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('labels', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('feed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
