# Generated by Django 3.2.25 on 2026-05-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='import_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
