# Generated by Django 3.2.25 on 2026-05-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_import_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='illustrated_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='illustrated_lng',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='location',
            name='poly_coords',
        ),
        migrations.RemoveField(
            model_name='location',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='location',
            name='profile_link',
        ),
    ]
