# Generated by Django 3.2.4 on 2022-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20220426_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='building_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='building_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
