# Generated by Django 3.2.25 on 2026-05-22 15:45

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_remove_legacy_api_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=locations.models._location_image_storage, upload_to=''),
        ),
    ]
