# Generated by Django 3.2.4 on 2022-04-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20220426_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='import_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
