# Generated by Django 3.2.4 on 2022-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_import_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='import_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='site_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
