# Generated by Django 3.2.4 on 2022-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20220427_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
