# Generated by Django 3.2.4 on 2022-04-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_campus_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='import_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
