# Generated by Django 3.2.4 on 2022-04-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_pointofinterest_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='facility_groups', to='locations.Facility'),
        ),
        migrations.AlterField(
            model_name='group',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='location_groups', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parking_lots',
            field=models.ManyToManyField(blank=True, related_name='parking_lot_groups', to='locations.ParkingLot'),
        ),
        migrations.AlterField(
            model_name='group',
            name='points_of_interest',
            field=models.ManyToManyField(blank=True, related_name='point_groups', to='locations.PointOfInterest'),
        ),
    ]
