# Generated by Django 3.2.13 on 2022-04-28 20:23

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20220428_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='photo',
            field=s3_file_field.fields.S3FileField(blank=True, null=True, upload_to='locations'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='photo',
            field=s3_file_field.fields.S3FileField(blank=True, null=True, upload_to='locations'),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=s3_file_field.fields.S3FileField(blank=True, null=True, upload_to='locations'),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='photo',
            field=s3_file_field.fields.S3FileField(blank=True, null=True, upload_to='locations'),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='photo',
            field=s3_file_field.fields.S3FileField(blank=True, null=True, upload_to='locations'),
        ),
    ]
