# Generated by Django 3.2.13 on 2022-11-17 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_auto_20221117_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='internallink',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internallink',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
